experiments: 
  - model: resnet 
    strategy: badge 
    initial_size: 5000 
    query_size: [500] 
    dataset: cifar10

  - model: resnet 
    strategy: random 
    initial_size: 5000 
    query_size: [500]
    dataset: cifar10


