experiments:
  - model: resnet
    strategy: badge
    initial_size: 500
    query_size: [100]
    dataset: cifar10 

  - model: resnet 
    strategy: random 
    initial_size: 500
    query_size: [100]
    dataset: cifar10
  
  
